configserver:
  name: JHipster Registry config server
  status: Connesso al JHipster Registry config server per FORMAZIONE, stai usando https://github.com/fchiri/spring-cloud-configuration
    !
jhipster:
  security:
    authentication:
      jwt:
        secret: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl
